'use strict';

var userPoints = 0;

console.log('hello');
alert('Welcome to my guessing game');

var user = prompt('What is your name?');
alert('Hi ' + user + '! I am so glad you want to play my game.');

var answer1 = prompt('Was Arthur\'s interest in tech sparked by a childhood visit to the Pacific Science Center?').toLowerCase();
console.log(answer1);

if (answer1 === 'yes' || answer1 === 'y') {
  userPoints++;
  alert('Yes! It\'s just outside the window of Code Fellows, so that was an easy question.');
}else{
  alert('Wrong! Actually, I\'m sure many generations of Seattle childen learned about tech at the Pacific Science Center.');
}
alert('You have ' + userPoints + ' points.');

var answer2 = prompt('Was Arthur\'s tech interest at PSC specifically generated by a solar powered transisitor radio?').toLowerCase();
console.log(answer2);

if (answer2 === 'yes' || answer2 === 'y') {
  userPoints++;
  alert('I guess so.  That is the earliest memory I have of the museum, of exhibits that were no longer there on future visits.');
}else{
  alert('Actually, I\'m not entirely sure, but it the earliest memory of an exhibit that was not there on future visits.');
}
alert('You have ' + userPoints + ' points.');

var answer3 = prompt('Did Arthur also get to go to the Seattle Children\'s Museum?').toLowerCase();
console.log(answer3);
if (answer3 === 'no' || answer3 === 'n') {
  userPoints++;
  alert('Oh, I wish I had gone there as a child, but it was at Pioneer Square then, and I never got taken there.');
}else{
  alert('Sadly, no is yes.  The museum was at Pioneer Square then, and I never got taken there until I was an adult.');
}
alert('You have ' + userPoints + ' points.');

var answer4 = prompt('Was Arthur\'s tech interst also sparked by looking at road maps?').toLowerCase();
console.log(answer4);
if (answer4 === 'yes' || answer4 === 'y') {
  userPoints++;
  alert('Yes, Arthur was a weird kid, and was fascinated by networks and connections.');
}else{
  alert('Wrong! Actually Arthur was interested in maps because of all the networks and connections they showed.');
}
alert('You have ' + userPoints + ' points.');

var answer5 = prompt('Did Arthur write his own versions of Tetris and Columns in AppleSoft BASIC?').toLowerCase();
console.log(answer5);
if (answer5 === 'yes' || answer5 === 'y') {
  userPoints++;
  alert('But of course, who doesn\'t do these things?  He wrote Tetris in 1991 and Columns in 2017');
}else{
  alert('Actually, BASIC is an easy language to write, especially if graphics are included.');
}
alert('You have ' + userPoints + ' points.');

//ending statements here?
